version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: invoices-postgres
    profiles: ["postgres"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-invoices_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - invoices-network

  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: invoices-oracle
    profiles: ["oracle"]
    environment:
      ORACLE_PWD: ${ORACLE_PASSWORD:-Oracle123}
      ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET:-AL32UTF8}
    ports:
      - "${ORACLE_PORT:-1521}:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - invoices-network
    shm_size: 1gb

  invoices-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoices-service
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: http://+:3002
      DatabaseSettings__UseOracle: ${USE_ORACLE:-false}
      DatabaseSettings__PostgresConnection: ${POSTGRES_CONNECTION}
      DatabaseSettings__OracleConnection: ${ORACLE_CONNECTION}
      ExternalServices__CustomersApiUrl: ${CUSTOMERS_API_URL:-http://host.docker.internal:3001}
    ports:
      - "${INVOICES_PORT:-3002}:3002"
    depends_on:
      postgres:
        condition: service_healthy
        required: false
      oracle:
        condition: service_healthy
        required: false
    networks:
      - invoices-network
    profiles: ["invoices"]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: invoices-pgadmin
    profiles: ["dev-tools"]
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@invoices.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - invoices-network

volumes:
  postgres_data:
    driver: local
  oracle_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  invoices-network:
    driver: bridge
